export default interface ISubscriptionItem {
  id: string;
  firstName: string;
  lastName: string;
  linkCompany: string;
  linkJob: string;
  companyName: string;
  emailAddress: string;
  jobTitle: string;
  category: string;
  specialities: string | string[];
  skills: string | string[];
  gameGenres: string | string[];
  gameEngines: string | string[];
  gamePlatforms: string | string[];
  seniorityLevel: string;
  artAndAnimationStyles: string | string[];
  employmentOptions: string;
  workPreferences: string;
  country: string;
  roleLocation: string;
  ip: string;
  salaryRange: string;
  responsibilities: string;
  requirements: string;
  jobDescription: string;
  benefits: string | null;
  logoFile: any;
  user_agent: string;
  referrer: string;
  created_at: string;
}
